"""initial schema

Revision ID: 7fcd0b2e9897
Revises: 
Create Date: 2026-10-06 16:01:45.256031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcd0b2e9897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('eui64', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('cloud_remote_server_token', sa.String(length=36), nullable=False),
    sa.Column('web_admin_password', sa.String(length=64), nullable=False),
    sa.Column('web_securized', sa.Boolean(), nullable=False),
    sa.Column('knet_id', sa.Integer(), nullable=True),
    sa.Column('image_version', sa.String(length=64), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('link', sa.String(length=20), nullable=False),
    sa.Column('link_kick_dts', sa.DateTime(), nullable=True),
    sa.Column('linked_dts', sa.DateTime(), nullable=True),
    sa.Column('delete_requested_dts', sa.DateTime(), nullable=True),
    sa.Column('datetimestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_eui64'), ['eui64'], unique=True)

    op.create_table('device_logs',
    sa.Column('device_log_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('eui64', sa.String(length=16), nullable=True),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('datetimestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_log_id')
    )
    with op.batch_alter_table('device_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_logs_datetimestamp'), ['datetimestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_logs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_logs_eui64'), ['eui64'], unique=False)

    op.create_table('portal_devices',
    sa.Column('portal_device_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('portal_name', sa.String(length=120), nullable=False),
    sa.Column('datetimestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portal_device_id'),
    sa.UniqueConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portal_devices')
    with op.batch_alter_table('device_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_logs_eui64'))
        batch_op.drop_index(batch_op.f('ix_device_logs_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_logs_datetimestamp'))

    op.drop_table('device_logs')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_eui64'))

    op.drop_table('devices')
    # ### end Alembic commands ###
